# Generated by Django 6.0 on 2026-01-25 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('bill_period_from', models.DateField(blank=True, null=True)),
                ('bill_period_to', models.DateField(blank=True, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('EXPIRED', 'Expired')], default='UNPAID', max_length=20)),
                ('biller_reference', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bills',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='BillerCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Biller Categories',
                'db_table': 'biller_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('biller_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('convenience_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('convenience_fee_flat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_instant_payment', models.BooleanField(default=True)),
                ('processing_time_hours', models.IntegerField(default=0)),
                ('supports_bill_fetch', models.BooleanField(default=True)),
                ('customer_id_label', models.CharField(default='Customer ID', max_length=100)),
                ('customer_id_format', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billers', to='bill_payments.billercategory')),
            ],
            options={
                'db_table': 'billers',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedBiller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('billing_address', models.TextField(blank=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('is_autopay_enabled', models.BooleanField(default=False)),
                ('autopay_amount_type', models.CharField(choices=[('FULL', 'Full Amount'), ('FIXED', 'Fixed Amount'), ('MINIMUM', 'Minimum Due')], default='FULL', max_length=20)),
                ('autopay_fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('autopay_due_days_before', models.IntegerField(default=3)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_payments.biller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_billers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_billers',
                'ordering': ['-is_favorite', 'nickname'],
                'unique_together': {('user', 'biller', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='RecurringBillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly'), ('WEEKLY', 'Weekly'), ('BI_MONTHLY', 'Bi-Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('BILL_AMOUNT', 'Full Bill Amount'), ('MINIMUM', 'Minimum Due')], max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_amount_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(choices=[('ACCOUNT', 'Bank Account'), ('UPI', 'UPI'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('WALLET', 'Digital Wallet')], max_length=20)),
                ('from_account_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('next_execution_date', models.DateField()),
                ('last_executed_date', models.DateField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('max_failed_attempts', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bill_payments', to=settings.AUTH_USER_MODEL)),
                ('saved_biller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to='bill_payments.savedbiller')),
            ],
            options={
                'db_table': 'recurring_bill_payments',
                'ordering': ['next_execution_date'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('ACCOUNT', 'Bank Account'), ('UPI', 'UPI'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('WALLET', 'Digital Wallet')], max_length=20)),
                ('from_account_number', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('biller_transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('is_autopay', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bill_payments.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to=settings.AUTH_USER_MODEL)),
                ('saved_biller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bill_payments.savedbiller')),
            ],
            options={
                'db_table': 'bill_payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='saved_biller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bill_payments.savedbiller'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('saved_biller', 'bill_number', 'bill_date')},
        ),
    ]
