# Generated by Django 6.0 on 2026-01-09 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CLEAR', 'Clear'), ('SUSPICIOUS', 'Suspicious'), ('CONFIRMED_FRAUD', 'Confirmed Fraud'), ('FALSE_POSITIVE', 'False Positive')], default='SUSPICIOUS', max_length=20)),
                ('risk_score', models.PositiveIntegerField()),
                ('reasons', models.JSONField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
