# Generated by Django 5.0.1 on 2026-03-07 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_initial'),
        ('transactions', '0003_alter_idempotencykey_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraudflag',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['status'], name='fraud_fraud_status_9d8b64_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['-created_at'], name='fraud_fraud_created_5a7e99_idx'),
        ),
    ]
