# Generated by Django 6.0.1 on 2026-01-25 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('minimum_credit_limit', models.DecimalField(decimal_places=2, default=10000, max_digits=15)),
                ('maximum_credit_limit', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('cash_advance_limit_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('minimum_income_requirement', models.DecimalField(decimal_places=2, default=300000, max_digits=15)),
                ('reward_points_per_100', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credit_card_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('requested_credit_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employment_type', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=200)),
                ('work_experience_months', models.IntegerField()),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('existing_credit_cards', models.IntegerField(default=0)),
                ('existing_loans_emi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('approved_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_credit_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_applications', to=settings.AUTH_USER_MODEL)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_cards.creditcardtype')),
            ],
            options={
                'db_table': 'credit_card_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_advance_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_cash_advance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_date', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('pin_set', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('reward_points', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_statement_date', models.DateField(blank=True, null=True)),
                ('next_statement_date', models.DateField(blank=True, null=True)),
                ('minimum_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_cards.creditcardapplication')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_cards.creditcardtype')),
            ],
            options={
                'db_table': 'credit_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('CASH_ADVANCE', 'Cash Advance'), ('PAYMENT', 'Payment'), ('INTEREST', 'Interest Charge'), ('FEE', 'Fee'), ('REFUND', 'Refund'), ('REWARD_REDEMPTION', 'Reward Redemption')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('merchant_category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('authorization_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=20)),
                ('reward_points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('foreign_currency', models.CharField(blank=True, max_length=3)),
                ('foreign_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credit_cards.creditcard')),
            ],
            options={
                'db_table': 'credit_card_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField()),
                ('due_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minimum_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reward_points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward_points_redeemed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_payment_received', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='credit_cards.creditcard')),
            ],
            options={
                'db_table': 'credit_card_statements',
                'ordering': ['-statement_date'],
                'unique_together': {('credit_card', 'statement_date')},
            },
        ),
    ]
