# Generated by Django 5.0.1 on 2026-03-06 18:27

import credit_cards.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='cvv',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=credit_cards.encryption.EncryptedCharField(max_length=16),
        ),
    ]
