# Generated by Django 5.0.1 on 2026-03-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_options_and_more'),
        ('transactions', '0003_alter_idempotencykey_key_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-created_at'], name='transaction_account_b1cc5a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
    ]
